directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
productName: AMXX-BG Youtube Downloader
appId: com.amxxbg.amxxbg
asar: true
publish: null
mac:
  icon: assets/icons/512x512.png
  extraResources:
    - ./node_modules/ffmpeg-static/bin/darwin/x64
    - ./node_modules/ffprobe-static/bin/darwin/x64
win:
  icon: assets/icons/512x512.png
  extraResources:
    - ./node_modules/ffmpeg-static/bin/win32/x64
    - ./node_modules/ffprobe-static/bin/win32/x64
linux:
  icon: assets/icons/256x256.png
  extraResources:
    - ./node_modules/ffmpeg-static/bin/linux/x64
    - ./node_modules/ffprobe-static/bin/linux/x64
electronVersion: 5.0.6
